### Fera formidável 4.1 - " Quem classifica a classe classificadora?"

Alunos: José Victor da Silva Izidório e Lucas Nascimento da Silva

#### Enunciado

Objetivo: altere a rede neural feita em Python puro para resolver um problema de
classificação. Treine uma rede neural em um dataset simples de classificação para mostrar
que funciona.

Comentário: aqui é necessário se informar sobre as diferenças de uma rede neural
classificadora com relação a uma rede neural regressora. A função de perda, por exemplo,
não poderá ser mais a função de perda dos resíduos quadrados.


In [14]:
import math
import random
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [15]:
df = pd.read_csv("/Users/lucas24025/Downloads/Redes Neurais/diabetes_dataset.csv")
df 

Unnamed: 0  Age     Sex Ethnicity   BMI  Waist_Circumference  \
0              0   58  Female     White  35.8                 83.4   
1              1   48    Male     Asian  24.1                 71.4   
2              2   34  Female     Black  25.0                113.8   
3              3   62    Male     Asian  32.7                100.4   
4              4   27  Female     Asian  33.5                110.8   
...          ...  ...     ...       ...   ...                  ...   
9995        9995   45  Female     Asian  39.4                114.0   
9996        9996   41  Female     Asian  21.0                 71.3   
9997        9997   50  Female     Asian  29.0                106.3   
9998        9998   62  Female     White  27.3                119.9   
9999        9999   29    Male     Black  20.6                102.0   

      Fasting_Blood_Glucose  HbA1c  Blood_Pressure_Systolic  \
0                     123.9   10.9                      152   
1                     183.7   12.8                      103   
2                     142.0   14.5                      179   
3                     167.4    8.8                      176   
4                     146.4    7.1                      122   
...                     ...    ...                      ...   
9995                   76.2   13.4                      109   
9996                   77.1   12.9                      154   
9997                   97.5    4.9                      122   
9998                   89.0   11.5                       99   
9999                   70.8   14.5                      156   

      Blood_Pressure_Diastolic  ...  Cholesterol_HDL  Cholesterol_LDL   GGT  \
0                          114  ...             50.2             99.2  37.5   
1                           91  ...             62.0            146.4  88.5   
2                          104  ...             32.1            164.1  56.2   
3                          118  ...             41.1             84.0  34.4   
4                           97  ...             53.9             92.8  81.9   
...                        ...  ...              ...              ...   ...   
9995                        82  ...             60.3             88.7  19.1   
9996                        72  ...             72.3            200.0  37.1   
9997                        61  ...             69.8            156.1  85.8   
9998                       115  ...             74.2            110.9  25.3   
9999                        64  ...             38.0            108.1  68.5   

      Serum_Urate  Physical_Activity_Level Dietary_Intake_Calories  \
0             7.2                 Moderate                    1538   
1             6.1                 Moderate                    2653   
2             6.9                      Low                    1684   
3             5.4                      Low                    3796   
4             7.4                 Moderate                    3161   
...           ...                      ...                     ...   
9995          6.1                      Low                    3582   
9996          3.5                      Low                    2206   
9997          4.9                     High                    3175   
9998          5.2                     High                    3478   
9999          6.0                      Low                    2918   

      Alcohol_Consumption Smoking_Status Family_History_of_Diabetes  \
0                Moderate          Never                          0   
1                Moderate        Current                          0   
2                   Heavy         Former                          1   
3                Moderate          Never                          1   
4                   Heavy        Current                          0   
...                   ...            ...                        ...   
9995                  NaN         Former                          1   
9996                  NaN          Never          

In [32]:
# Entradas
BMI = df["BMI"]
Blood_Pressure_Systolic = df["Blood_Pressure_Systolic"]
Cholesterol_LDL = df["Cholesterol_LDL"]
HbA1c = df["HbA1c"]
Waist_Circumference = df["Waist_Circumference"]
Fasting_Blood_Glucose = df["Fasting_Blood_Glucose"]
Physical_Activity_Level = df["Physical_Activity_Level"]

# Target
Physical_Activity_Level = df["Physical_Activity_Level"]
Physical_Activity_Level

0       Moderate
1       Moderate
2            Low
3            Low
4       Moderate
          ...   
9995         Low
9996         Low
9997        High
9998        High
9999         Low
Name: Physical_Activity_Level, Length: 10000, dtype: object

In [33]:
Physical_Activity_Level = Physical_Activity_Level.values.reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(Physical_Activity_Level)

Physical_Activity_Level_onehot = encoder.transform(Physical_Activity_Level)

print(f"Dados originais: \n{Physical_Activity_Level}")
print()
print(f"Dados convertidos em onehot: \n{Physical_Activity_Level_onehot}")

Dados originais: 
[['Moderate']
 ['Moderate']
 ['Low']
 ...
 ['High']
 ['High']
 ['Low']]

Dados convertidos em onehot: 
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [4]:
class Valor:
    def __init__(self, data, progenitor=(), operador_mae="", rotulo=""):
        self.data = data
        self.progenitor = progenitor
        self.operador_mae = operador_mae
        self.rotulo = rotulo
        self.grad = 0

    def __repr__(self):
        return f"Valor(data={self.data})"
    
    def __add__(self, outro_valor):
        """Realiza a operação: self + outro_valor."""
        
        if not isinstance(outro_valor, Valor):
            outro_valor = Valor(outro_valor)
            
        progenitor = (self, outro_valor)
        data = self.data + outro_valor.data
        operador_mae = "+"
        resultado = Valor(data, progenitor, operador_mae)
        
        def propagar_adicao():
            self.grad += resultado.grad
            outro_valor.grad += resultado.grad
            
        resultado.propagar = propagar_adicao
        
        return resultado
    
    def __mul__(self, outro_valor):
        """Realiza a operação: self * outro_valor."""
        
        if not isinstance(outro_valor, Valor):
            outro_valor = Valor(outro_valor)
            
        progenitor = (self, outro_valor)
        data = self.data * outro_valor.data
        operador_mae = "*"
        resultado = Valor(data, progenitor, operador_mae)
        
        def propagar_multiplicacao():
            self.grad += resultado.grad * outro_valor.data # grad_filho * derivada filho em relação a mãe
            outro_valor.grad += resultado.grad * self.data
            
        resultado.propagar = propagar_multiplicacao
        
        return resultado
    
    def exp(self):
        """Realiza a operação: exp(self)"""
        progenitor = (self, )
        data = math.exp(self.data)
        operador_mae = "exp"
        resultado = Valor(data, progenitor, operador_mae)
        
        def propagar_exp():
            self.grad += resultado.grad * data 
        
        resultado.propagar = propagar_exp
        
        return resultado
    
    def __pow__(self, expoente):
        """Realiza a operação: self ** expoente"""
        assert isinstance(expoente, (int, float))
        progenitor = (self, )
        data = self.data ** expoente
        operador_mae = f"**{expoente}"
        resultado = Valor(data, progenitor, operador_mae)
        
        def propagar_pow():
            self.grad += resultado.grad * (expoente * self.data ** (expoente - 1))
        
        resultado.propagar = propagar_pow
        
        return resultado
    
    def __truediv__(self, outro_valor):
        """Realiza a operação: self / outro_valor"""
        return self * outro_valor ** (-1)
    
    def __neg__(self):
        """Realiza a operação: -self"""
        return self * -1
    
    def __sub__(self, outro_valor):
        """Realiza a operação: self - outro_valor"""
        return self + (-outro_valor)
    
    def __radd__(self, outro_valor):
        """Realiza a operação: outro_valor + self"""
        return self + outro_valor
    
    def __rmul__(self, outro_valor):
        """Realiza a operação: outro_valor * self"""
        return self * outro_valor
    
    def sig(self):
        """Realiza a operação: exp(self) / (exp(self) + 1)"""
        return self.exp() / (self.exp() + 1)
    
    def propagar(self):
        pass
    
    def propagar_tudo(self):
        
        self.grad = 1
        
        ordem_topologica = []
        
        visitados = set()

        def constroi_ordem_topologica(v):
            if v not in visitados:
                visitados.add(v)
                for progenitor in v.progenitor:
                    constroi_ordem_topologica(progenitor)
                ordem_topologica.append(v)

        constroi_ordem_topologica(self)
        
        for vertice in reversed(ordem_topologica):
            vertice.propagar()

In [5]:
class Neuronio:
    def __init__(self, num_dados_entrada):
        self.vies = Valor(random.uniform(-1, 1))
        
        self.pesos = []
        for i in range(num_dados_entrada):
            self.pesos.append(Valor(random.uniform(-1, 1)))
            
    def __call__(self, x):
        
        assert len(x) == len(self.pesos)
        
        soma = 0
        for info_entrada, peso_interno in zip(x, self.pesos):
            soma += info_entrada * peso_interno
            
        soma += self.vies  
        dado_de_saida = soma.sig()
        
        return dado_de_saida       
    
    def parametros(self):
        return self.pesos + [self.vies]

In [6]:
class Camada:
    def __init__(self, num_neuronios, num_dados_entrada):
        neuronios = []
        
        for _ in range(num_neuronios):
            neuronio = Neuronio(num_dados_entrada)
            neuronios.append(neuronio)
            
        self.neuronios = neuronios     
        
    def __call__(self, x):
        dados_de_saida = []
        
        for neuronio in self.neuronios:
            informacao = neuronio(x)
            dados_de_saida.append(informacao)
            
        if len(dados_de_saida) == 1:
            return dados_de_saida[0]
        else:        
            return dados_de_saida  
    
    def parametros(self):
        params = []
        
        for neuronio in self.neuronios:
            params_neuronio = neuronio.parametros()
            params.extend(params_neuronio)
        
        return params

In [7]:
class MLP:
    def __init__(self, num_dados_entrada, num_neuronios_por_camada):
        
        percurso = [num_dados_entrada] + num_neuronios_por_camada
        
        camadas = []
        
        for i in range(len(num_neuronios_por_camada)):
            camada = Camada(num_neuronios_por_camada[i], percurso[i])
            camadas.append(camada)
            
        self.camadas = camadas
        
    def __call__(self, x):
        for camada in self.camadas:
            x = camada(x)
        return x
    
    def parametros(self):
        params = []
        
        for camada in self.camadas:
            parametros_camada = camada.parametros()
            params.extend(parametros_camada)
            
        return params

In [9]:
NUM_EPOCAS = 2000
TAXA_DE_APRENDIZADO = 0.5
 
x = [
  lista_BMI,
  lista_Blood_Pressure_Systolic,
  lista_Cholesterol_LDL,
  lista_HbA1c,
  lista_Waist_Circumference,
  lista_Fasting_Blood_Glucose
]
 
y_true = lista
 
for epoca in range(NUM_EPOCAS):
    # forward pass
    y_pred = []
    for exemplo in x:
        previsao = minha_mlp(exemplo)
        y_pred.append(previsao)
 
    # loss
    erros = []
    for yt, yp in zip(y_true, y_pred):
        residuo = yp - yt
        erro_quadratico = residuo ** 2
        erros.append(erro_quadratico)        
    loss = sum(erros)
 
    # zero grad
    for p in minha_mlp.parametros():
        p.grad = 0
 
    # backpropagation
    loss.propagar_tudo()
 
    # atualiza parâmetros
    for p in minha_mlp.parametros():
        p.data = p.data - p.grad * TAXA_DE_APRENDIZADO
 
    # mostra resultado (opcional)
    print(epoca, loss.data)

NameError: name 'lista_BMI' is not defined